#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1364979193.775769
__CHEETAH_genTimestamp__ = 'Wed Apr  3 17:53:13 2013'
__CHEETAH_src__ = '/home/fermi/Work/Model/tmsingle/openpli3.0/build-tmsingle/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-openwebif-0.1+git1+279a2577c3bc6defebd4bf9e61a046dcf7f37c01-r0.72/git/plugin/controllers/views/mobile/channelinfo.tmpl'
__CHEETAH_srcLastModified__ = 'Wed Apr  3 17:10:17 2013'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class channelinfo(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(channelinfo, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<html>\r
 <head>\r
\t<title>OpenWebif</title>\r
\t<meta name="viewport" content="user-scalable=no, width=device-width"/>\r
\t<meta name="apple-mobile-web-app-capable" content="yes" />\r
\t<link rel="stylesheet" type="text/css" href="/css/jquery.mobile-1.0.min.css" media="screen"/>\r
\t<link rel="stylesheet" type="text/css" href="/css/iphone.css" media="screen"/>\r
\t<script src="/js/jquery-1.6.2.min.js"></script>\r
\t<script src="/js/jquery.mobile-1.0.min.js"></script>\r
 </head>\r
 <body> \r
\t<div data-role="page">\r
\r
\t\t<div id="header">\r
\t\t\t<div class="button" onClick="history.back()">Back</div>\r
\t\t\t<h1>OpenWebif</h1>\r
\t\t</div>\r
\r
\t\t<div id="mainContent" class="ui-corner-all">\r
\t\t\t<table width="100%" border="0" cellspacing="1" cellpadding="5">
\t\t\t\t\t\t<tr>
\t\t\t\t\t\t\t<th colspan="3" class="ui-btn-up-b" style="text-align: left;">Service</th>
\t\t\t\t\t\t</tr>
\t\t\t\t\t\t<tr style="background-color:  #f0f7fc;">
\t\t\t\t\t\t\t<td width="200"><img src="''')
        _v = VFFSL(SL,"channelinfo.picon",True) # u'$channelinfo.picon' on line 25, col 34
        if _v is not None: write(_filter(_v, rawExpr=u'$channelinfo.picon')) # from line 25, col 34.
        write(u'''" border="0" alt=""></td>\r
\t\t\t\t\t\t\t<td width="100%" valign="top">\r
\t\t\t\t\t\t\t<strong>''')
        _v = VFFSL(SL,"channelinfo.sname",True) # u'$channelinfo.sname' on line 27, col 16
        if _v is not None: write(_filter(_v, rawExpr=u'$channelinfo.sname')) # from line 27, col 16.
        write(u'''</strong><br />\r
\t\t\t\t\t\t\t''')
        _v = VFFSL(SL,"channelinfo.title",True) # u'$channelinfo.title' on line 28, col 8
        if _v is not None: write(_filter(_v, rawExpr=u'$channelinfo.title')) # from line 28, col 8.
        write(u'''<br />\r
\t\t\t\t\t\t\t''')
        _v = VFFSL(SL,"channelinfo.begin",True) # u'$channelinfo.begin' on line 29, col 8
        if _v is not None: write(_filter(_v, rawExpr=u'$channelinfo.begin')) # from line 29, col 8.
        write(u'''-''')
        _v = VFFSL(SL,"channelinfo.end",True) # u'$channelinfo.end' on line 29, col 27
        if _v is not None: write(_filter(_v, rawExpr=u'$channelinfo.end')) # from line 29, col 27.
        write(u''' (''')
        _v = VFFSL(SL,"channelinfo.duration",True) # u'$channelinfo.duration' on line 29, col 45
        if _v is not None: write(_filter(_v, rawExpr=u'$channelinfo.duration')) # from line 29, col 45.
        write(u''' min)<br />\r
\t\t\t\t\t\t\t</td>
\t\t\t\t\t\t</tr>
\t\t\t\t\t\t<tr>
\t\t\t\t\t\t\t<th colspan="2" class="ui-btn-up-b" style="text-align: left;">Current Event</th>
\t\t\t\t\t\t</tr>\r
''')
        if VFFSL(SL,"channelinfo.shortdesc",True): # generated from line 35, col 7
            write(u'''\t\t\t\t\t\t<tr style="background-color:  #f0f7fc;">
\t\t\t\t\t\t\t<td colspan="2">''')
            _v = VFFSL(SL,"channelinfo.shortdesc",True) # u'$channelinfo.shortdesc' on line 37, col 24
            if _v is not None: write(_filter(_v, rawExpr=u'$channelinfo.shortdesc')) # from line 37, col 24.
            write(u'''</td>
\t\t\t\t\t\t</tr>\r
''')
        if VFFSL(SL,"channelinfo.longdesc",True): # generated from line 40, col 7
            write(u'''\t\t\t\t\t\t<tr style="background-color:  #f0f7fc;">
\t\t\t\t\t\t\t<td colspan="2">''')
            _v = VFFSL(SL,"channelinfo.longdesc",True) # u'$channelinfo.longdesc' on line 42, col 24
            if _v is not None: write(_filter(_v, rawExpr=u'$channelinfo.longdesc')) # from line 42, col 24.
            write(u'''</td>
\t\t\t\t\t\t</tr>
''')
        write(u'''\t\t\t</table>\r
\t\t</div>\r
\t\t\r
\t\t<div id="contentContainer">\r
\t\t\t<ul data-role="listview" data-inset="true" data-theme="d">\r
\t\t\t\t<li data-role="list-divider" role="heading" data-theme="b">Upcoming Events</li>\r
''')
        for event in VFFSL(SL,"channelepg",True): # generated from line 51, col 5
            write(u'''\t\t\t\t<li style="padding: 3px;">\r
\t\t\t\t\t<span class="ui-li-heading" style="margin-top: 0px; margin-bottom: 3px;">''')
            _v = VFFSL(SL,"event.title",True) # u'$event.title' on line 53, col 79
            if _v is not None: write(_filter(_v, rawExpr=u'$event.title')) # from line 53, col 79.
            write(u'''</span>\r
\t\t\t\t\t<span class="ui-li-desc" style="margin-bottom: 0px;">''')
            _v = VFFSL(SL,"event.begin",True) # u'$event.begin' on line 54, col 59
            if _v is not None: write(_filter(_v, rawExpr=u'$event.begin')) # from line 54, col 59.
            write(u''' - ''')
            _v = VFFSL(SL,"event.end",True) # u'$event.end' on line 54, col 74
            if _v is not None: write(_filter(_v, rawExpr=u'$event.end')) # from line 54, col 74.
            write(u'''</span>\r
\t\t\t\t</li>\r
''')
        write(u'''\t\t\t</ul>\r
\t\t</div>\r
\r
\t\t<div id="footer">\r
\t\t\t<p>OpenWebif Mobile</p>\r
\t\t</div>\r
\t\t\r
\t</div>\r
 </body>\r
</html>\r
      ''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_channelinfo= 'respond'

## END CLASS DEFINITION

if not hasattr(channelinfo, '_initCheetahAttributes'):
    templateAPIClass = getattr(channelinfo, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(channelinfo)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=channelinfo()).run()


